### ISSUE TITLE
publish it, pls

### ISSUE THREAD

**Issue by iamstarkov** [bloodyowl/immutable-date#2]
https://www.npmjs.com/package/bloody-immutable-date links to https://github.com/bloodyowl/flux
At the same time current package.json contains correct link, so just publish new version

**Comment by bloodyowl** [comment]
sorry about that, fixed

![screen shot 2015-06-21 at 23 50 37](https://cloud.githubusercontent.com/assets/1688645/8273473/5a234244-1870-11e5-9d18-87a4c402480c.png)

**Comment by iamstarkov** [comment]
:+1:
